service: iot-cold-chain-monitoring-server
frameworkVersion: '3'

custom:
  stage: 'dev'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${self:custom.stage}
  region: eu-west-1

resources:
  Resources:
    CognitoUserPool: ${file(resources/cognito-users.yml):CognitoUserPool}
    CognitoUserPoolClient: ${file(resources/cognito-users.yml):CognitoUserPoolClient}

functions:
  signIn:
    handler: src/handlers/auth.signIn
    events:
      - httpApi:
          path: /auth/signin
          method: POST
          cors: true

  signUp:
    handler: src/handlers/auth.signUp
    events:
      - httpApi:
          path: /auth/signup
          method: POST
          cors: true