CognitoUserPool:
  Type: "AWS::Cognito::UserPool"
  Properties:
    MfaConfiguration: OFF
    UserPoolName: ${self:service}-${self:provider.stage}-user-pool
    UsernameAttributes:
      - email
    Policies:
      PasswordPolicy:
        MinimumLength: 6
        RequireLowercase: False
        RequireNumbers: False
        RequireSymbols: False
        RequireUppercase: False

CognitoUserPoolClient:
  Type: "AWS::Cognito::UserPoolClient"
  Properties:
    ClientName: ${self:service}-${self:custom.stage}-user-pool-client
    GenerateSecret: False
    UserPoolId:
      Ref: CognitoUserPool

# Cognito roles @see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolgroup.html
UnauthorizedGroup:
  Type: AWS::Cognito::UserPoolGroup
  Properties:
    GroupName: Unauthorized
    Precedence: Null
#    RoleArn: TODO add appropriate IAM role
    UserPoolId:
      Ref: CognitoUserPool

OrganizationGroup:
  Type: AWS::Cognito::UserPoolGroup
  Properties:
    GroupName: Organization
    Precedence: Null
    #    RoleArn: TODO add appropriate IAM role
    UserPoolId:
      Ref: CognitoUserPool

OperatorGroup:
  Type: AWS::Cognito::UserPoolGroup
  Properties:
    GroupName: Operator
    Precedence: Null
    #    RoleArn: TODO add appropriate IAM role
    UserPoolId:
      Ref: CognitoUserPool
