CognitoUserPool:
  Type: "AWS::Cognito::UserPool"
  Properties:
    MfaConfiguration: OFF
    UserPoolName: ${self:service}-${self:custom.stage}-user-pool
    UsernameAttributes:
      - email
    Policies:
      PasswordPolicy:
        MinimumLength: 6
        RequireLowercase: False
        RequireNumbers: False
        RequireSymbols: False
        RequireUppercase: False

CognitoUserPoolClient:
  Type: "AWS::Cognito::UserPoolClient"
  Properties:
    ClientName: ${self:service}-${self:custom.stage}-user-pool-client
    GenerateSecret: False
    UserPoolId:
      Ref: CognitoUserPool